all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  hosts:
    server-3:
      ansible_host: 10.10.10.127
      ansible_user: server-3
      ansible_become_pass: "ituma123456789"
    ituma:
      ansible_host: 10.10.10.121
      ansible_user: ituma
      ansible_become_pass: "ituma123456789"
