all:
  hosts:
    ubuntu2:
      ansible_host: 10.10.10.127
      ansible_user: server-3
      ansible_password: ituma123456789
      ansible_sudo_pass: ituma123456789
      ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no'
    ubuntu3:
      ansible_host: 10.10.10.121
      ansible_user: ituma
      ansible_password: ituma123456789
      ansible_sudo_pass: ituma123456789
      ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no'
