---
- name: System-Einrichtung und Benutzererstellung
  hosts: all
  become: yes
  vars:
    # Generierte SHA-512 Hashes für die Benutzer
    user_passwords:
      miki: "$6$gjiKVaZbvRyba2wl$jENpLDrqfqVIpy0jZoQmkqNq/W.Quz7yTQlaCIYOHj/KRRBwvBWHjjN7hwMn0CSVfykMUBxaNmIvEoRfslI59."
      abdu: "$6$2QCL.Edq9Ap4DGWY$lWcFqbyhvQXgm5FWbFVoT5ObUVg3RWKV8OifELNLv2zNIStABCybvsBrvlvEzn9GAlszpzu20i.uGBGSTScK90"
      ousama: "$6$gjiKVaZbvRyba2wl$jENpLDrqfqVIpy0jZoQmkqNq/W.Quz7yTQlaCIYOHj/KRRBwvBWHjjN7hwMn0CSVfykMUBxaNmIvEoRfslI59."

  tasks:
    - name: Erforderliche Pakete installieren (nano, wireguard, tcpdump, git)
      apt:
        name:
          - nano
          - wireguard
          - tcpdump
          - git
        state: present
        update_cache: yes

    - name: Benutzerkonto fuer Miki erstellen
      user:
        name: miki
        password: "{{ user_passwords.miki }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    - name: Benutzerkonto fuer Abdu erstellen
      user:
        name: abdu
        password: "{{ user_passwords.abdu }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    - name: Eigenes Benutzerkonto erstellen (abderrahmane)
      user:
        name: abderrahmane
        password: "{{ user_passwords.myself }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
