- name: Update und Upgrade auf Ubuntu Target-Servern
  hosts: all
  become: yes
  tasks:
    - name: Paketlisten aktualisieren (apt update)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Alle installierten Pakete aktualisieren (apt upgrade)
      apt:
        upgrade: dist
